timeagent:
   values:
      agent-name: my-first-agent
      max-limit-search: 50
      swagger:
         title: timeagent
         description: "scheduled or manual execution of agents"
         version: 0.1.0-SNAPSHOT
         license: "Apache License, Version 2.0"
         license-url: "https://www.apache.org/licenses/LICENSE-2.0"
         contact:
            company: smithx
            url: "https://www.smithx.org"
            mail: mail@smithx.org
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbcUrl: jdbc:mariadb://localhost:3306/timeagent
      username: root
      password: mariadb
spring:
   jpa:
      show-sql: false
      hibernate:
         ddl-auto: update
server:
   servlet:
      context-path: /timeagent
management:
   endpoint:
      health:
         show-details: ALWAYS
